package pl.electricshop.user_service.model.enums;

public enum Country {
    // European Countries
    Albania,
    Andorra,
    Armenia,
    Austria,
    Azerbaijan,
    Belarus,
    Belgium,
    Bosnia_and_Herzegovina,
    Bulgaria,
    Croatia,
    Cyprus,
    Czech_Republic,
    Denmark,
    Estonia,
    Finland,
    France,
    Georgia,
    Germany,
    Greece,
    Hungary,
    Iceland,
    Ireland,
    Italy,
    Kazakhstan,
    Kosovo,
    Latvia,
    Liechtenstein,
    Lithuania,
    Luxembourg,
    Malta,
    Moldova,
    Monaco,
    Montenegro,
    Netherlands,
    North_Macedonia,
    Norway,
    Poland,
    Portugal,
    Romania,
    Russia,
    San_Marino,
    Serbia,
    Slovakia,
    Slovenia,
    Spain,
    Sweden,
    Switzerland,
    Turkey,
    Ukraine,
    United_Kingdom,
    Vatican_City,

    // Non-European Countries
    USA,
    Other
}
