server:
  port: 8080

# JWT Configuration - RS256 with public key only (for validation)
app:
  jwt:
    public-key: classpath:certs/public.pem
  gateway:
    public-paths:
      - /api/v1/auth/**
      - /api/v1/products/**
      - /api/v1/categories/**
      - /actuator/**

# gRPC Client Configuration
grpc:
  client:
    user-service:
      address: ${GRPC_CLIENT_USER_SERVICE_ADDRESS:static://localhost:9091}
      negotiation-type: plaintext

spring:
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/api/v1/users/**,/api/v1/auth/**
        - id: product-service
          uri: lb://product-service
          predicates:
            - Path=/api/v1/products/**,/api/v1/categories/**,/api/v1/admin/**
        - id: cart-service
          uri: lb://cart-service
          predicates:
            - Path=/api/v1/cart/**
        - id: order-service
          uri: lb://order-service
          predicates:
            - Path=/api/v1/orders/**
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders: "*"
