server:
  port: 8084

spring:
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}

# gRPC Client
grpc:
  client:
    product-service:
      address: ${GRPC_CLIENT_PRODUCT_SERVICE_ADDRESS:static://localhost:9090}
      negotiation-type: plaintext
