server:
  port: 8085

spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/electric_shop_db
    username: ${POSTGRES_USER:electric_user}
    password: ${POSTGRES_PASSWORD:electric_password}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        default_schema: orders
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration
    table: order_schema_version
    schemas: orders
    default-schema: orders
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
  cloud:
    stream:
      kafka:
        binder:
          brokers: ${KAFKA_BROKERS:localhost:9092}
