server:
  port: 8083

spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/electric_shop_db
    username: ${POSTGRES_USER:electric_user}
    password: ${POSTGRES_PASSWORD:electric_password}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        default_schema: products
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration
    table: product_schema_version
    schemas: products
    default-schema: products

# gRPC Server
grpc:
  server:
    port: 9090

# Image configuration
project:
  image: images/
  default: default_image.png

image:
  base:
    url: http://localhost:8080/images
