server:
  port: 8083

spring:
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST:localhost}:${POSTGRES_PORT:5433}/${POSTGRES_DB:electric_shop_db}
    username: ${POSTGRES_USER:electric_user}
    password: ${POSTGRES_PASSWORD:electric_password}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        default_schema: products

  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration
    table: product_schema_version
    schemas: products
    default-schema: products

  # Kafka Configuration
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.add.type.headers: true

# gRPC Server Configuration
grpc:
  server:
    port: 9090

# Image configuration
project:
  image: images/
  default: default_image.png

image:
  base:
    url: ${IMAGE_BASE_URL:http://localhost:8080/images}
