server:
  port: 8081

# gRPC Server Configuration
grpc:
  server:
    port: 9091

spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/electric_shop_db
    username: ${POSTGRES_USER:electric_user}
    password: ${POSTGRES_PASSWORD:electric_password}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        default_schema: users
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration
    table: user_schema_version
    schemas: users
    default-schema: users
